apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argo-cd-cert
spec:
  secretName: argocd-secret
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: argo.0001118.xyz
  dnsNames:
    - argo.0001118.xyz
