apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: infisical
spec:
  provider:
    infisical: # (https://external-secrets.io/latest/provider/infisical/)
      hostAPI: https://app.infisical.com
      auth:
        universalAuthCredentials: # (https://external-secrets.io/latest/provider/infisical/#universal-auth)
          clientId:
            name: infisical-secret
            namespace: external-secrets
            key: clientId
          clientSecret:
            name: infisical-secret
            namespace: external-secrets
            key: clientSecret
      secretsScope: # (https://external-secrets.io/latest/provider/infisical/#secrets-scope-configuration)
        projectSlug: argo-cd-93b-q
        environmentSlug: prod
        # Optional variables
        secretsPath: / # The base path for secrets retrieval (default: /)
        recursive: false # When true, fetches secrets recursively from subfolders (default: false)
        expandSecretReferences: true # When true, expand secret references (e.g., `${SECRET_NAME}`) (default: true)
