apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jerichokeyne/argocd-files
    path: argocd
    targetRevision: master
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /spec/replicas
    - group: external-secrets.io # Needed due to "ServerSideApply=true"
      kind: ExternalSecret
      jsonPointers:
        - /spec/data/*/conversionStrategy
        - /spec/data/*/decodingStrategy
        - /spec/data/*/metadataPolicy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      refresh: true
    syncOptions:
      - ServerSideApply=true
